title: MSU Denver - CS Resources
description: Aimed primarily at students, this should serve as a useful place to go to for self-guided learning resources for leaning Computer Science and Software Engineering fundamentals.
theme: jekyll-theme-minimal
