title: MSU Denver - CS Resources
description: Aimed at giving students a useful place to go to for learning resources, this is a compilation of things I personally found to be helpful in my own self-guided learning and would like to share. 
theme: jekyll-theme-minimal
